apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: mjaillais2
  description: test Matthieu 2
  annotations: 
    github.com/project-slug: criteo-dexter/mjaillais2
    backstage.io/github-actions-id: criteo-dexter/mjaillais2
    jenkins.io/github-folder: 'job/thirdparty-garmadon'
spec:
  type: openapi
  lifecycle: production
  owner: mjaadev
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
